name: FirstPlugin
version: '1.0'
main: me.toi.firstplugin.FirstPlugin
api-version: 1.18
authors: [ TOI ]
description: My 1st Plugin
commands:
  admininfo:
    description: gives info, used for dev testing
    #Alias doesn't work idk why
    aliases: [ai]
    usage: /<command> [player] [info] [Args]
